apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tq9debgcu-nodejs
  janus-idp.io/tekton: tq9debgcu-nodejs
  backstage.io/kubernetes-id: tq9debgcu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tq9debgcu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
